Update update_stars.yml

diff --git a/.github/workflows/update_stars.yml b/.github/workflows/update_stars.yml
--- a/.github/workflows/update_stars.yml
+++ b/.github/workflows/update_stars.yml
@@ -2,38 +2,43 @@ name: Update GitHub Stars
 
 on:
   schedule:
-    - cron: '0 0 * * *' # Runs daily at midnight
-  workflow_dispatch: # Allows manual triggering of the workflow
+    - cron: '0 0 * * *'  # Runs daily at midnight
+  workflow_dispatch:  # Allows manual triggering of the workflow
 
 jobs:
   update-stars:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v2
+      - name: Checkout repository
+        uses: actions/checkout@v2
 
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: '3.x'
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.x'
 
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install requests
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install requests
 
-    - name: Run script
-      env:
-        MY_GITHUB_USERNAME: ${{ secrets.MY_GITHUB_USERNAME }}
-        RANDOKEY: ${{ secrets.RANDOKEY }}
-      run: |
-        python fetch_and_generate.py
+      - name: Run script
+        env:
+          MY_GITHUB_USERNAME: ${{ secrets.MY_GITHUB_USERNAME }}
+          RANDOKEY: ${{ secrets.RANDOKEY }}
+        run: |
+          python fetch_and_generate.py
 
-    - name: Commit and push changes if index.md is updated
-      run: |
-        git config --local user.email "action@github.com"
-        git config --local user.name "GitHub Action"
-        git add index.md
-        git diff --cached --exit-code || git commit -m "Update GitHub Stars"
-        git push origin main
+      - name: Commit and push changes if index.md is updated
+        run: |
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git add index.md
+          git diff --cached --exit-code || git commit -m "Update GitHub Stars"
+          git_push_attempt=1
+          while ! git push origin main; do
+            echo "Push failed. Retrying attempt $git_push_attempt..."
+            git_push_attempt=$((git_push_attempt + 1))
+            sleep 5  # Wait before retrying
+          done
